import { defineConfig, globalIgnores } from "eslint/config"
import nextVitals from "eslint-config-next/core-web-vitals"

export default defineConfig([
  globalIgnores([
    ".next/**",
    ".next-docs/**",
    "out/**",
    "build/**",
    "node_modules/**",
    "next-env.d.ts",
    // Generated by `pnpm generate-typings` (gql.tada), which rewrites it whole on
    // every run — including its own blanket directive. Linting it can only ever
    // report on a file the next run discards.
    "src/lib/datocms/graphql-env.d.ts",
  ]),
  ...nextVitals,
  {
    // The DatoCMS private plugin is an isolated artifact that runs inside the
    // CMS's iframe. The SDK hands `ctx` in imperatively and iframe detection is
    // client-only, so these rules would only prescribe rewrites against the
    // plugin contract. Scoped here rather than disabled repo-wide.
    files: ["src/app/(plugin)/private-datocms-plugin/**/*.{ts,tsx}"],
    rules: {
      "react-hooks/set-state-in-effect": "off",
      "react-hooks/exhaustive-deps": "off",
    },
  },
])
