/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Tag = {
  _id: string
  _type: "tag"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
}

export type Standings = {
  _id: string
  _type: "standings"
  _createdAt: string
  _updatedAt: string
  _rev: string
  league?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "league"
  }
  division?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "division"
  }
  season?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "season"
  }
  teams?: Array<{
    team?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "team"
    }
    gamesPlayed?: number
    wins?: number
    losses?: number
    draws?: number
    pointsFor?: number
    pointsAgainst?: number
    difference?: number
    bonusPointTries?: number
    bonusPointLoss?: number
    forfeits?: number
    points?: number
    leaguePointsPerGame?: number
    _type: "teamData"
    _key: string
  }>
}

export type SponsorBar = {
  _id: string
  _type: "sponsorBar"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  items?: Array<{
    sponsor?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sponsor"
    }
    _type: "sponsorItem"
    _key: string
  }>
}

export type Sponsor = {
  _id: string
  _type: "sponsor"
  _createdAt: string
  _updatedAt: string
  _rev: string
  sponsorName?: string
  sponsorLogo?: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  url?: string
  nofollow?: boolean
  openInNewTab?: boolean
  width?: number
  height?: number
}

export type SocialMedia = {
  _id: string
  _type: "socialMedia"
  _createdAt: string
  _updatedAt: string
  _rev: string
  facebook?: string
  instagram?: string
  youtube?: string
  twitter?: string
}

export type Settings = {
  _id: string
  _type: "settings"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal"
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
  ogImage?: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: "image"
  }
}

export type Seo = {
  _id: string
  _type: "seo"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  keywords?: Array<string>
  canonicalUrl?: string
  robots?: string
  ogTitle?: string
  ogDescription?: string
  ogImage?: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  ogUrl?: string
  twitterTitle?: string
  twitterDescription?: string
  twitterImage?: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
}

export type RichText = {
  _type: "richText"
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?:
      | "normal"
      | "h1"
      | "h1-lg"
      | "h2"
      | "h3"
      | "h4"
      | "h5"
      | "h6"
      | "blockquote"
    listItem?: "bullet" | "number"
    markDefs?: Array<
      | {
          href?: string
          blank?: boolean
          _type: "link"
          _key: string
        }
      | {
          reference?:
            | {
                _ref: string
                _type: "reference"
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: "page"
              }
            | {
                _ref: string
                _type: "reference"
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: "post"
              }
            | {
                _ref: string
                _type: "reference"
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: "product"
              }
          _type: "internalLink"
          _key: string
        }
      | ({
          _key: string
        } & TextColor)
      | ({
          _key: string
        } & HighlightColor)
    >
    level?: number
    _type: "block"
    _key: string
  }>
  spacing_top?: 0 | 8 | 16 | 24 | 32 | 40
  spacing_bottom?: 0 | 8 | 16 | 24 | 32 | 40
  gap?: 0 | 8 | 16 | 24 | 32 | 40
}

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote"
      listItem?: "bullet" | "number"
      markDefs?: Array<{
        href?: string
        _type: "link"
        _key: string
      }>
      level?: number
      _type: "block"
      _key: string
    }
  | ({
      _key: string
    } & BlockGroup)
  | {
      asset?: {
        _ref: string
        _type: "reference"
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
      _key: string
    }
  | {
      asset?: {
        _ref: string
        _type: "reference"
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      caption?: string
      _type: "imageWithCaption"
      _key: string
    }
  | ({
      _key: string
    } & MediaText)
  | ({
      _key: string
    } & Columns)
  | ({
      _key: string
    } & Button)
  | ({
      _key: string
    } & ButtonGroup)
>

export type PageBuilder = Array<
  | ({
      _key: string
    } & Heading)
  | ({
      _key: string
    } & RichText)
  | ({
      _key: string
    } & LinkGroup)
>

export type Navigation = {
  _id: string
  _type: "navigation"
  _createdAt: string
  _updatedAt: string
  _rev: string
  mainNav?: Array<{
    item?:
      | {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "page"
        }
      | {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "post"
        }
      | {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "product"
        }
    customLink?: string
    overrideTitle?: string
    submenu?: Array<{
      item?:
        | {
            _ref: string
            _type: "reference"
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: "page"
          }
        | {
            _ref: string
            _type: "reference"
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: "post"
          }
        | {
            _ref: string
            _type: "reference"
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: "product"
          }
      customLink?: string
      overrideTitle?: string
      route?: string
      openInNewTab?: boolean
      _key: string
    }>
    route?: string
    openInNewTab?: boolean
    _key: string
  }>
  footerNav?: Array<{
    item?:
      | {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "page"
        }
      | {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "post"
        }
      | {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "product"
        }
    customLink?: string
    overrideTitle?: string
    submenu?: Array<{
      item?:
        | {
            _ref: string
            _type: "reference"
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: "page"
          }
        | {
            _ref: string
            _type: "reference"
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: "post"
          }
        | {
            _ref: string
            _type: "reference"
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: "product"
          }
      customLink?: string
      overrideTitle?: string
      route?: string
      openInNewTab?: boolean
      _key: string
    }>
    route?: string
    openInNewTab?: boolean
    _key: string
  }>
}

export type MediaText = {
  _type: "mediaText"
  image?: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  text?: PortableText
}

export type Match = {
  _id: string
  _type: "match"
  _createdAt: string
  _updatedAt: string
  _rev: string
  eventDateTime?: string
  league?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "league"
  }
  division?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "division"
  }
  season?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "season"
  }
  matchType?: "competitive" | "friendly"
  homeTeam?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "team"
  }
  awayTeam?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "team"
  }
  name?: string
  homeTeamScore?: number
  awayTeamScore?: number
}

export type Team = {
  _id: string
  _type: "team"
  _createdAt: string
  _updatedAt: string
  _rev: string
  teamName?: string
  teamLogo?: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  league?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "league"
  }
  division?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "division"
  }
  shortName?: string
}

export type Season = {
  _id: string
  _type: "season"
  _createdAt: string
  _updatedAt: string
  _rev: string
  year?: number
  season?: "Fall" | "Spring"
}

export type Linktree = {
  _id: string
  _type: "linktree"
  _createdAt: string
  _updatedAt: string
  _rev: string
  primaryGroupTitle?: string
  primaryLinks?: Array<{
    label?: string
    internalLink?:
      | {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "page"
        }
      | {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "post"
        }
      | {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "product"
        }
    customLink?: string
    route?: string
    openInNewTab?: boolean
    _key: string
  }>
  secondaryGroupTitle?: string
  secondaryLinks?: Array<{
    label?: string
    internalLink?:
      | {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "page"
        }
      | {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "post"
        }
      | {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "product"
        }
    customLink?: string
    route?: string
    openInNewTab?: boolean
    _key: string
  }>
}

export type LinkGroup = {
  _type: "linkGroup"
  links?: Array<
    {
      _key: string
    } & Link
  >
  alignment?: "left" | "center" | "right"
}

export type Link = {
  _type: "link"
  text?: string
  reference?:
    | {
        _ref: string
        _type: "reference"
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: "page"
      }
    | {
        _ref: string
        _type: "reference"
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: "post"
      }
    | {
        _ref: string
        _type: "reference"
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: "product"
      }
  customLink?: string
  route?: string
  openInNewTab?: boolean
  asButton?: boolean
  style?: string
}

export type League = {
  _id: string
  _type: "league"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  shortName?: string
}

export type ImageWithCaption = {
  _type: "imageWithCaption"
  asset?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
  }
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  caption?: string
}

export type Homepage = {
  _id: string
  _type: "homepage"
  _createdAt: string
  _updatedAt: string
  _rev: string
  pageBuilder?: PageBuilder
  seo?: {
    title?: string
    description?: string
    keywords?: Array<string>
    canonicalUrl?: string
    robots?: string
    ogTitle?: string
    ogDescription?: string
    ogImage?: {
      asset?: {
        _ref: string
        _type: "reference"
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    ogUrl?: string
    twitterTitle?: string
    twitterDescription?: string
    twitterImage?: {
      asset?: {
        _ref: string
        _type: "reference"
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    _type: "seo"
  }
}

export type Heading = {
  _type: "heading"
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h1" | "h1-lg" | "h2" | "h3" | "h4" | "h5" | "h6"
    listItem?: never
    markDefs?: Array<
      | {
          href?: string
          blank?: boolean
          _type: "link"
          _key: string
        }
      | {
          reference?:
            | {
                _ref: string
                _type: "reference"
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: "page"
              }
            | {
                _ref: string
                _type: "reference"
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: "post"
              }
            | {
                _ref: string
                _type: "reference"
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: "product"
              }
          _type: "internalLink"
          _key: string
        }
      | ({
          _key: string
        } & TextColor)
      | ({
          _key: string
        } & HighlightColor)
    >
    level?: number
    _type: "block"
    _key: string
  }>
  spacing_top?: 0 | 8 | 16 | 24 | 32 | 40
  spacing_bottom?: 0 | 8 | 16 | 24 | 32 | 40
  gap?: 0 | 8 | 16 | 24 | 32 | 40
}

export type Product = {
  _id: string
  _type: "product"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  specs?: Array<{
    lang?: string
    title?: string
    content?: string
    _type: "spec"
    _key: string
  }>
  addons?: {
    title?: string
    products?: Array<{
      _ref: string
      _type: "reference"
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: "product"
    }>
  }
  form?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "formType"
  }
}

export type Post = {
  _id: string
  _type: "post"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  date?: string
  modified?: string
  status?:
    | "publish"
    | "future"
    | "draft"
    | "pending"
    | "private"
    | "trash"
    | "auto-draft"
    | "inherit"
  content?: PortableText
  excerpt?: PortableText
  featuredMedia?: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  sticky?: boolean
  author?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "author"
  }
  categories?: Array<{
    _ref: string
    _type: "reference"
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: "category"
  }>
  tags?: Array<{
    _ref: string
    _type: "reference"
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: "tag"
  }>
}

export type Page = {
  _id: string
  _type: "page"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  date?: string
  modified?: string
  status?:
    | "publish"
    | "future"
    | "draft"
    | "pending"
    | "private"
    | "trash"
    | "auto-draft"
    | "inherit"
  content?: PortableText
  excerpt?: PortableText
  featuredMedia?: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  author?: {
    _ref: string
    _type: "reference"
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: "author"
  }
}

export type FormFieldType = {
  _type: "formFieldType"
  label?: string
  name?: string
  type?:
    | "text"
    | "email"
    | "password"
    | "number"
    | "textarea"
    | "select"
    | "checkbox"
    | "radio"
    | "date"
  placeholder?: string
  required?: boolean
  options?: Array<string>
  defaultValue?: string
  helpText?: string
  minLength?: number
  maxLength?: number
  pattern?: string
}

export type FormType = {
  _id: string
  _type: "formType"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  formFields?: Array<{
    label?: string
    fieldType?: "text" | "email" | "textarea" | "select" | "checkbox"
    required?: boolean
    options?: Array<string>
    fieldName?: string
    placeholder?: string
    _type: "formField"
    _key: string
  }>
}

export type Division = {
  _id: string
  _type: "division"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  shortName?: string
}

export type Columns = {
  _type: "columns"
  columns?: Array<
    {
      _key: string
    } & Column
  >
}

export type Column = {
  _type: "column"
  content?: PortableText
}

export type Category = {
  _id: string
  _type: "category"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
}

export type Calendar = {
  _type: "calendar"
  title?: string
  events?: Array<{
    eventDateTime?: string
    league?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "league"
    }
    division?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "division"
    }
    season?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "season"
    }
    matchType?: "competitive" | "friendly"
    homeTeam?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "team"
    }
    awayTeam?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "team"
    }
    name?: string
    homeTeamScore?: number
    awayTeamScore?: number
    _type: "match"
    _key: string
  }>
}

export type ButtonGroup = {
  _type: "buttonGroup"
  buttons?: Array<
    {
      _key: string
    } & Button
  >
}

export type Button = {
  _type: "button"
  text?: string
  url?: string
  style?: string
  target?: "_self" | "_blank"
  rel?: string
}

export type BlockGroup = {
  _type: "blockGroup"
  children?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: "span"
          _key: string
        }>
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote"
        listItem?: "bullet" | "number"
        markDefs?: Array<{
          href?: string
          _type: "link"
          _key: string
        }>
        level?: number
        _type: "block"
        _key: string
      }
    | ({
        _key: string
      } & BlockGroup)
    | {
        asset?: {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: "image"
        _key: string
      }
    | ({
        _key: string
      } & ImageWithCaption)
    | ({
        _key: string
      } & MediaText)
    | ({
        _key: string
      } & Columns)
    | ({
        _key: string
      } & Button)
    | ({
        _key: string
      } & ButtonGroup)
  >
}

export type Author = {
  _id: string
  _type: "author"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  url?: string
  description?: string
  avatar?: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
}

export type HighlightColor = {
  _type: "highlightColor"
  label?: string
  value?: string
}

export type TextColor = {
  _type: "textColor"
  label?: string
  value?: string
}

export type SimplerColor = {
  _type: "simplerColor"
  label?: string
  value?: string
}

export type MediaTag = {
  _id: string
  _type: "media.tag"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type AllSanitySchemaTypes =
  | Tag
  | Standings
  | SponsorBar
  | Sponsor
  | SocialMedia
  | Settings
  | Seo
  | RichText
  | PortableText
  | PageBuilder
  | Navigation
  | MediaText
  | Match
  | Team
  | Season
  | Linktree
  | LinkGroup
  | Link
  | League
  | ImageWithCaption
  | Homepage
  | Heading
  | Product
  | Post
  | Page
  | FormFieldType
  | FormType
  | Division
  | Columns
  | Column
  | Category
  | Calendar
  | ButtonGroup
  | Button
  | BlockGroup
  | Author
  | HighlightColor
  | TextColor
  | SimplerColor
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./src/app/(main)/[slug]/pages.query.ts
// Variable: pageQuery
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    date,    modified,    status,    content,    excerpt,    coverImage,    featuredMedia{      asset->{        url      },      alt    },    author->{name}  }
export type PageQueryResult = {
  _id: string
  title: string | null
  slug: string | null
  date: string | null
  modified: string | null
  status:
    | "auto-draft"
    | "draft"
    | "future"
    | "inherit"
    | "pending"
    | "private"
    | "publish"
    | "trash"
    | null
  content: PortableText | null
  excerpt: PortableText | null
  coverImage: null
  featuredMedia: {
    asset: {
      url: string | null
    } | null
    alt: null
  } | null
  author: {
    name: string | null
  } | null
} | null
// Variable: pagesSlugs
// Query: *[_type == "page" && defined(slug.current)]  {"slug": slug.current}
export type PagesSlugsResult = Array<{
  slug: string | null
}>

// Source: ./src/app/(main)/matches/all/schedule.query.ts
// Variable: scheduleQuery
// Query: *[_type == "match"] {    _id,    eventDateTime,    league-> {      _id,      name    },    division-> {      _id,      name    },    season-> {      _id,      name    },    matchType,    homeTeam-> {      _id,      name    },    awayTeam-> {      _id,      name    },    name,    homeTeamScore,    awayTeamScore  } | order(eventDateTime asc)
export type ScheduleQueryResult = Array<{
  _id: string
  eventDateTime: string | null
  league: {
    _id: string
    name: string | null
  } | null
  division: {
    _id: string
    name: string | null
  } | null
  season: {
    _id: string
    name: null
  } | null
  matchType: "competitive" | "friendly" | null
  homeTeam: {
    _id: string
    name: null
  } | null
  awayTeam: {
    _id: string
    name: null
  } | null
  name: string | null
  homeTeamScore: number | null
  awayTeamScore: number | null
}>

// Source: ./src/app/(main)/post/[slug]/posts.query.ts
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug] [0] {    content[]{    ...,    markDefs[]{      ...,        _type == "link" => {    "post": post->slug.current  }    }  },      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  featuredMedia,  sticky,  categories[]->{title},  tags[]->{title},  "date": coalesce(date, _updatedAt),  "modified": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type PostQueryResult = {
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: "span"
          _key: string
        }>
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal"
        listItem?: "bullet" | "number"
        markDefs: Array<{
          href?: string
          _type: "link"
          _key: string
          post: null
        }> | null
        level?: number
        _type: "block"
        _key: string
      }
    | {
        _key: string
        _type: "blockGroup"
        children?: Array<
          | ({
              _key: string
            } & BlockGroup)
          | ({
              _key: string
            } & Button)
          | ({
              _key: string
            } & ButtonGroup)
          | ({
              _key: string
            } & Columns)
          | ({
              _key: string
            } & ImageWithCaption)
          | ({
              _key: string
            } & MediaText)
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: "span"
                _key: string
              }>
              style?:
                | "blockquote"
                | "h1"
                | "h2"
                | "h3"
                | "h4"
                | "h5"
                | "h6"
                | "normal"
              listItem?: "bullet" | "number"
              markDefs?: Array<{
                href?: string
                _type: "link"
                _key: string
              }>
              level?: number
              _type: "block"
              _key: string
            }
          | {
              asset?: {
                _ref: string
                _type: "reference"
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
              }
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: "image"
              _key: string
            }
        >
        markDefs: null
      }
    | {
        _key: string
        _type: "button"
        text?: string
        url?: string
        style?: string
        target?: "_blank" | "_self"
        rel?: string
        markDefs: null
      }
    | {
        _key: string
        _type: "buttonGroup"
        buttons?: Array<
          {
            _key: string
          } & Button
        >
        markDefs: null
      }
    | {
        _key: string
        _type: "columns"
        columns?: Array<
          {
            _key: string
          } & Column
        >
        markDefs: null
      }
    | {
        asset?: {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: "image"
        _key: string
        markDefs: null
      }
    | {
        asset?: {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        caption?: string
        _type: "imageWithCaption"
        _key: string
        markDefs: null
      }
    | {
        _key: string
        _type: "mediaText"
        image?: {
          asset?: {
            _ref: string
            _type: "reference"
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
          }
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: "image"
        }
        text?: PortableText
        markDefs: null
      }
  > | null
  _id: string
  status: "draft" | "published"
  title: string | "Untitled"
  slug: string | null
  excerpt: PortableText | null
  coverImage: null
  featuredMedia: {
    asset?: {
      _ref: string
      _type: "reference"
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  } | null
  sticky: boolean | null
  categories: Array<{
    title: null
  }> | null
  tags: Array<{
    title: null
  }> | null
  date: string
  modified: string
  author: {
    firstName: null
    lastName: null
    picture: null
  } | null
} | null
// Variable: postPagesSlugs
// Query: *[_type == "post" && defined(slug.current)]  {"slug": slug.current}
export type PostPagesSlugsResult = Array<{
  slug: string | null
}>

// Source: ./src/components/footer/footer.nav.query.ts
// Variable: footerNavQuery
// Query: *[_type == "navigation"] | order(publishedAt desc)[0] {    footerNav[] {      item->{_id, title, slug, _type},      customLink,      overrideTitle,      openInNewTab,      route,      submenu[]{        item->{_id, title, slug, _type},        customLink,        overrideTitle,        openInNewTab,        route      }    }  }
export type FooterNavQueryResult = {
  footerNav: Array<{
    item:
      | {
          _id: string
          title: string | null
          slug: Slug | null
          _type: "page"
        }
      | {
          _id: string
          title: string | null
          slug: Slug | null
          _type: "post"
        }
      | {
          _id: string
          title: string | null
          slug: Slug | null
          _type: "product"
        }
      | null
    customLink: string | null
    overrideTitle: string | null
    openInNewTab: boolean | null
    route: string | null
    submenu: Array<{
      item:
        | {
            _id: string
            title: string | null
            slug: Slug | null
            _type: "page"
          }
        | {
            _id: string
            title: string | null
            slug: Slug | null
            _type: "post"
          }
        | {
            _id: string
            title: string | null
            slug: Slug | null
            _type: "product"
          }
        | null
      customLink: string | null
      overrideTitle: string | null
      openInNewTab: boolean | null
      route: string | null
    }> | null
  }> | null
} | null

// Source: ./src/components/header/nav.query.ts
// Variable: navQuery
// Query: *[_type == "navigation"] | order(publishedAt desc)[0] {    mainNav[] {      item->{_id, title, slug, _type},      customLink,      overrideTitle,      openInNewTab,      route,      submenu[]{        item->{_id, title, slug, _type},        customLink,        overrideTitle,        openInNewTab,        route      }    }  }
export type NavQueryResult = {
  mainNav: Array<{
    item:
      | {
          _id: string
          title: string | null
          slug: Slug | null
          _type: "page"
        }
      | {
          _id: string
          title: string | null
          slug: Slug | null
          _type: "post"
        }
      | {
          _id: string
          title: string | null
          slug: Slug | null
          _type: "product"
        }
      | null
    customLink: string | null
    overrideTitle: string | null
    openInNewTab: boolean | null
    route: string | null
    submenu: Array<{
      item:
        | {
            _id: string
            title: string | null
            slug: Slug | null
            _type: "page"
          }
        | {
            _id: string
            title: string | null
            slug: Slug | null
            _type: "post"
          }
        | {
            _id: string
            title: string | null
            slug: Slug | null
            _type: "product"
          }
        | null
      customLink: string | null
      overrideTitle: string | null
      openInNewTab: boolean | null
      route: string | null
    }> | null
  }> | null
} | null

// Source: ./src/components/sponsor-bar/sponsor.query.ts
// Variable: sponsorQuery
// Query: *[_type == "sponsorBar"] | order(publishedAt desc)[0] {    title,    items[] {      sponsor-> {        _id,        sponsorName,        sponsorLogo,        url,        nofollow,        openInNewTab,        width,        height      }    }  }
export type SponsorQueryResult = {
  title: string | null
  items: Array<{
    sponsor: {
      _id: string
      sponsorName: string | null
      sponsorLogo: {
        asset?: {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: "image"
      } | null
      url: string | null
      nofollow: boolean | null
      openInNewTab: boolean | null
      width: number | null
      height: number | null
    } | null
  }> | null
} | null

// Query TypeMap
import "@sanity/client"
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "page" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    date,\n    modified,\n    status,\n    content,\n    excerpt,\n    coverImage,\n    featuredMedia{\n      asset->{\n        url\n      },\n      alt\n    },\n    author->{name}\n  }': PageQueryResult
    '\n  *[_type == "page" && defined(slug.current)]\n  {"slug": slug.current}\n': PagesSlugsResult
    '\n  *[_type == "match"] {\n    _id,\n    eventDateTime,\n    league-> {\n      _id,\n      name\n    },\n    division-> {\n      _id,\n      name\n    },\n    season-> {\n      _id,\n      name\n    },\n    matchType,\n    homeTeam-> {\n      _id,\n      name\n    },\n    awayTeam-> {\n      _id,\n      name\n    },\n    name,\n    homeTeamScore,\n    awayTeamScore\n  } | order(eventDateTime asc)\n': ScheduleQueryResult
    '\n  *[_type == "post" && slug.current == $slug] [0] {\n    content[]{\n    ...,\n    markDefs[]{\n      ...,\n      \n  _type == "link" => {\n    "post": post->slug.current\n  }\n\n    }\n  },\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  featuredMedia,\n  sticky,\n  categories[]->{title},\n  tags[]->{title},\n  "date": coalesce(date, _updatedAt),\n  "modified": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': PostQueryResult
    '\n  *[_type == "post" && defined(slug.current)]\n  {"slug": slug.current}\n': PostPagesSlugsResult
    '*[_type == "navigation"] | order(publishedAt desc)[0] {\n    footerNav[] {\n      item->{_id, title, slug, _type},\n      customLink,\n      overrideTitle,\n      openInNewTab,\n      route,\n      submenu[]{\n        item->{_id, title, slug, _type},\n        customLink,\n        overrideTitle,\n        openInNewTab,\n        route\n      }\n    }\n  }': FooterNavQueryResult
    '*[_type == "navigation"] | order(publishedAt desc)[0] {\n    mainNav[] {\n      item->{_id, title, slug, _type},\n      customLink,\n      overrideTitle,\n      openInNewTab,\n      route,\n      submenu[]{\n        item->{_id, title, slug, _type},\n        customLink,\n        overrideTitle,\n        openInNewTab,\n        route\n      }\n    }\n  }': NavQueryResult
    '*[_type == "sponsorBar"] | order(publishedAt desc)[0] {\n    title,\n    items[] {\n      sponsor-> {\n        _id,\n        sponsorName,\n        sponsorLogo,\n        url,\n        nofollow,\n        openInNewTab,\n        width,\n        height\n      }\n    }\n  }': SponsorQueryResult
  }
}
